server:
  port: '8080'
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: 'true'
          #lowerCaseServiceId: 'true'
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
            
        - id: employee-service
          uri: lb://employee-service
          predicates: 
            - Path=/employee-service/**
          filters:
            - RewritePath=/employee-service(?<segment>/?.*), $\{segment}        
  #main:
    #web-application-type: reactive
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
