server:
  port: '8080'
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lowerCaseServiceId: 'true'
  main:
    web-application-type: reactive
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
