server:
  port: '8084'
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirectUri: http://localhost:4200/callback
