server:
  port: '8084'
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 326421130250-oaa8tmrlpoq6327r8dkiiqbpi326a7p6.apps.googleusercontent.com
            client-secret: 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
            redirectUri: http://localhost:4200/callback
